# Generated by Django 5.0.2 on 2025-04-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsystem', '0002_patient_vitals_alert_patient_vitals_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
    ]
