# Generated by Django 5.0.2 on 2025-04-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsystem', '0003_patient_chief_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('neurologist', 'Neurologist')], default='technician', max_length=20),
        ),
    ]
