# Generated by Django 5.0.2 on 2025-04-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsystem', '0007_alert_acknowledged_alert_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='symptom_onset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpa_consent', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('consent_given_by', models.CharField(blank=True, max_length=100)),
                ('relationship_to_patient', models.CharField(blank=True, max_length=100)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patientsystem.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type', models.CharField(choices=[('CT', 'CT Scan'), ('MRI', 'MRI')], max_length=50)),
                ('findings', models.TextField()),
                ('stroke_type', models.CharField(choices=[('ischemic', 'Ischemic Stroke'), ('hemorrhagic', 'Hemorrhagic Stroke'), ('none', 'No Stroke')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='patientsystem.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='LabResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbc_wbc', models.FloatField(blank=True, null=True, verbose_name='WBC Count')),
                ('cbc_hgb', models.FloatField(blank=True, null=True, verbose_name='Hemoglobin')),
                ('cbc_plt', models.IntegerField(blank=True, null=True, verbose_name='Platelet Count')),
                ('bmp_glucose', models.FloatField(blank=True, null=True, verbose_name='Glucose')),
                ('bmp_creatinine', models.FloatField(blank=True, null=True, verbose_name='Creatinine')),
                ('inr', models.FloatField(blank=True, null=True, verbose_name='INR')),
                ('pt', models.FloatField(blank=True, null=True, verbose_name='Prothrombin Time')),
                ('ptt', models.FloatField(blank=True, null=True, verbose_name='PTT')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patientsystem.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='RecentEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_surgery', models.BooleanField(default=False)),
                ('recent_biopsy', models.BooleanField(default=False)),
                ('recent_head_trauma', models.BooleanField(default=False)),
                ('recent_stroke', models.BooleanField(default=False)),
                ('recent_mi', models.BooleanField(default=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_events', to='patientsystem.patient')),
            ],
        ),
    ]
